# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _libpygraphs
else:
    import _libpygraphs

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libpygraphs.delete_SwigPyIterator

    def value(self):
        return _libpygraphs.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _libpygraphs.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _libpygraphs.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _libpygraphs.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _libpygraphs.SwigPyIterator_equal(self, x)

    def copy(self):
        return _libpygraphs.SwigPyIterator_copy(self)

    def next(self):
        return _libpygraphs.SwigPyIterator_next(self)

    def __next__(self):
        return _libpygraphs.SwigPyIterator___next__(self)

    def previous(self):
        return _libpygraphs.SwigPyIterator_previous(self)

    def advance(self, n):
        return _libpygraphs.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _libpygraphs.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _libpygraphs.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _libpygraphs.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _libpygraphs.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _libpygraphs.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _libpygraphs.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _libpygraphs:
_libpygraphs.SwigPyIterator_swigregister(SwigPyIterator)

class Graph(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _libpygraphs.Graph_swiginit(self, _libpygraphs.new_Graph(*args))

    def directed(self):
        return _libpygraphs.Graph_directed(self)

    def node_number(self):
        return _libpygraphs.Graph_node_number(self)

    def edge_number(self):
        return _libpygraphs.Graph_edge_number(self)

    def insert(self, arg2):
        return _libpygraphs.Graph_insert(self, arg2)

    def erase(self, arg2):
        return _libpygraphs.Graph_erase(self, arg2)

    def link(self, arg2, arg3, arg4=1):
        return _libpygraphs.Graph_link(self, arg2, arg3, arg4)

    def unlink(self, arg2, arg3):
        return _libpygraphs.Graph_unlink(self, arg2, arg3)

    def degree(self, arg2):
        return _libpygraphs.Graph_degree(self, arg2)

    def degree_out(self, arg2):
        return _libpygraphs.Graph_degree_out(self, arg2)

    def degree_in(self, arg2):
        return _libpygraphs.Graph_degree_in(self, arg2)

    def contains(self, *args):
        return _libpygraphs.Graph_contains(self, *args)

    def weight(self, arg2, arg3):
        return _libpygraphs.Graph_weight(self, arg2, arg3)

    def nodes(self):
        return _libpygraphs.Graph_nodes(self)

    def neighbours(self, arg2):
        return _libpygraphs.Graph_neighbours(self, arg2)
    __swig_destroy__ = _libpygraphs.delete_Graph

# Register Graph in _libpygraphs:
_libpygraphs.Graph_swigregister(Graph)

class Digraph(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _libpygraphs.Digraph_swiginit(self, _libpygraphs.new_Digraph(*args))

    def directed(self):
        return _libpygraphs.Digraph_directed(self)

    def node_number(self):
        return _libpygraphs.Digraph_node_number(self)

    def edge_number(self):
        return _libpygraphs.Digraph_edge_number(self)

    def insert(self, arg2):
        return _libpygraphs.Digraph_insert(self, arg2)

    def erase(self, arg2):
        return _libpygraphs.Digraph_erase(self, arg2)

    def link(self, arg2, arg3, arg4=1):
        return _libpygraphs.Digraph_link(self, arg2, arg3, arg4)

    def unlink(self, arg2, arg3):
        return _libpygraphs.Digraph_unlink(self, arg2, arg3)

    def degree(self, arg2):
        return _libpygraphs.Digraph_degree(self, arg2)

    def degree_out(self, arg2):
        return _libpygraphs.Digraph_degree_out(self, arg2)

    def degree_in(self, arg2):
        return _libpygraphs.Digraph_degree_in(self, arg2)

    def contains(self, *args):
        return _libpygraphs.Digraph_contains(self, *args)

    def weight(self, arg2, arg3):
        return _libpygraphs.Digraph_weight(self, arg2, arg3)

    def nodes(self):
        return _libpygraphs.Digraph_nodes(self)

    def neighbours(self, arg2):
        return _libpygraphs.Digraph_neighbours(self, arg2)
    __swig_destroy__ = _libpygraphs.delete_Digraph

# Register Digraph in _libpygraphs:
_libpygraphs.Digraph_swigregister(Digraph)

class GraphEdges(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _libpygraphs.GraphEdges_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libpygraphs.GraphEdges___nonzero__(self)

    def __bool__(self):
        return _libpygraphs.GraphEdges___bool__(self)

    def __len__(self):
        return _libpygraphs.GraphEdges___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _libpygraphs.GraphEdges___getitem__(self, key)

    def __delitem__(self, key):
        return _libpygraphs.GraphEdges___delitem__(self, key)

    def has_key(self, key):
        return _libpygraphs.GraphEdges_has_key(self, key)

    def keys(self):
        return _libpygraphs.GraphEdges_keys(self)

    def values(self):
        return _libpygraphs.GraphEdges_values(self)

    def items(self):
        return _libpygraphs.GraphEdges_items(self)

    def __contains__(self, key):
        return _libpygraphs.GraphEdges___contains__(self, key)

    def key_iterator(self):
        return _libpygraphs.GraphEdges_key_iterator(self)

    def value_iterator(self):
        return _libpygraphs.GraphEdges_value_iterator(self)

    def __setitem__(self, *args):
        return _libpygraphs.GraphEdges___setitem__(self, *args)

    def asdict(self):
        return _libpygraphs.GraphEdges_asdict(self)

    def __init__(self, *args):
        _libpygraphs.GraphEdges_swiginit(self, _libpygraphs.new_GraphEdges(*args))

    def empty(self):
        return _libpygraphs.GraphEdges_empty(self)

    def size(self):
        return _libpygraphs.GraphEdges_size(self)

    def swap(self, v):
        return _libpygraphs.GraphEdges_swap(self, v)

    def begin(self):
        return _libpygraphs.GraphEdges_begin(self)

    def end(self):
        return _libpygraphs.GraphEdges_end(self)

    def clear(self):
        return _libpygraphs.GraphEdges_clear(self)

    def get_allocator(self):
        return _libpygraphs.GraphEdges_get_allocator(self)

    def count(self, x):
        return _libpygraphs.GraphEdges_count(self, x)

    def erase(self, *args):
        return _libpygraphs.GraphEdges_erase(self, *args)

    def find(self, x):
        return _libpygraphs.GraphEdges_find(self, x)
    __swig_destroy__ = _libpygraphs.delete_GraphEdges

# Register GraphEdges in _libpygraphs:
_libpygraphs.GraphEdges_swigregister(GraphEdges)

class GraphNodes(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _libpygraphs.GraphNodes_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libpygraphs.GraphNodes___nonzero__(self)

    def __bool__(self):
        return _libpygraphs.GraphNodes___bool__(self)

    def __len__(self):
        return _libpygraphs.GraphNodes___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _libpygraphs.GraphNodes___getitem__(self, key)

    def __delitem__(self, key):
        return _libpygraphs.GraphNodes___delitem__(self, key)

    def has_key(self, key):
        return _libpygraphs.GraphNodes_has_key(self, key)

    def keys(self):
        return _libpygraphs.GraphNodes_keys(self)

    def values(self):
        return _libpygraphs.GraphNodes_values(self)

    def items(self):
        return _libpygraphs.GraphNodes_items(self)

    def __contains__(self, key):
        return _libpygraphs.GraphNodes___contains__(self, key)

    def key_iterator(self):
        return _libpygraphs.GraphNodes_key_iterator(self)

    def value_iterator(self):
        return _libpygraphs.GraphNodes_value_iterator(self)

    def __setitem__(self, *args):
        return _libpygraphs.GraphNodes___setitem__(self, *args)

    def asdict(self):
        return _libpygraphs.GraphNodes_asdict(self)

    def __init__(self, *args):
        _libpygraphs.GraphNodes_swiginit(self, _libpygraphs.new_GraphNodes(*args))

    def empty(self):
        return _libpygraphs.GraphNodes_empty(self)

    def size(self):
        return _libpygraphs.GraphNodes_size(self)

    def swap(self, v):
        return _libpygraphs.GraphNodes_swap(self, v)

    def begin(self):
        return _libpygraphs.GraphNodes_begin(self)

    def end(self):
        return _libpygraphs.GraphNodes_end(self)

    def clear(self):
        return _libpygraphs.GraphNodes_clear(self)

    def get_allocator(self):
        return _libpygraphs.GraphNodes_get_allocator(self)

    def count(self, x):
        return _libpygraphs.GraphNodes_count(self, x)

    def erase(self, *args):
        return _libpygraphs.GraphNodes_erase(self, *args)

    def find(self, x):
        return _libpygraphs.GraphNodes_find(self, x)
    __swig_destroy__ = _libpygraphs.delete_GraphNodes

# Register GraphNodes in _libpygraphs:
_libpygraphs.GraphNodes_swigregister(GraphNodes)

class PriorityQueue(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _libpygraphs.PriorityQueue_swiginit(self, _libpygraphs.new_PriorityQueue(*args))

    def empty(self):
        return _libpygraphs.PriorityQueue_empty(self)

    def size(self):
        return _libpygraphs.PriorityQueue_size(self)

    def front(self):
        return _libpygraphs.PriorityQueue_front(self)

    def enqueue(self, arg2, arg3):
        return _libpygraphs.PriorityQueue_enqueue(self, arg2, arg3)

    def dequeue(self):
        return _libpygraphs.PriorityQueue_dequeue(self)

    def contains(self, arg2):
        return _libpygraphs.PriorityQueue_contains(self, arg2)

    def priority(self, arg2):
        return _libpygraphs.PriorityQueue_priority(self, arg2)

    def update(self, arg2, arg3):
        return _libpygraphs.PriorityQueue_update(self, arg2, arg3)

    def items(self):
        return _libpygraphs.PriorityQueue_items(self)
    __swig_destroy__ = _libpygraphs.delete_PriorityQueue

# Register PriorityQueue in _libpygraphs:
_libpygraphs.PriorityQueue_swigregister(PriorityQueue)

class PrioItems(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _libpygraphs.PrioItems_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libpygraphs.PrioItems___nonzero__(self)

    def __bool__(self):
        return _libpygraphs.PrioItems___bool__(self)

    def __len__(self):
        return _libpygraphs.PrioItems___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _libpygraphs.PrioItems___getitem__(self, key)

    def __delitem__(self, key):
        return _libpygraphs.PrioItems___delitem__(self, key)

    def has_key(self, key):
        return _libpygraphs.PrioItems_has_key(self, key)

    def keys(self):
        return _libpygraphs.PrioItems_keys(self)

    def values(self):
        return _libpygraphs.PrioItems_values(self)

    def items(self):
        return _libpygraphs.PrioItems_items(self)

    def __contains__(self, key):
        return _libpygraphs.PrioItems___contains__(self, key)

    def key_iterator(self):
        return _libpygraphs.PrioItems_key_iterator(self)

    def value_iterator(self):
        return _libpygraphs.PrioItems_value_iterator(self)

    def __setitem__(self, *args):
        return _libpygraphs.PrioItems___setitem__(self, *args)

    def asdict(self):
        return _libpygraphs.PrioItems_asdict(self)

    def __init__(self, *args):
        _libpygraphs.PrioItems_swiginit(self, _libpygraphs.new_PrioItems(*args))

    def empty(self):
        return _libpygraphs.PrioItems_empty(self)

    def size(self):
        return _libpygraphs.PrioItems_size(self)

    def swap(self, v):
        return _libpygraphs.PrioItems_swap(self, v)

    def begin(self):
        return _libpygraphs.PrioItems_begin(self)

    def end(self):
        return _libpygraphs.PrioItems_end(self)

    def clear(self):
        return _libpygraphs.PrioItems_clear(self)

    def get_allocator(self):
        return _libpygraphs.PrioItems_get_allocator(self)

    def count(self, x):
        return _libpygraphs.PrioItems_count(self, x)

    def erase(self, *args):
        return _libpygraphs.PrioItems_erase(self, *args)

    def find(self, x):
        return _libpygraphs.PrioItems_find(self, x)
    __swig_destroy__ = _libpygraphs.delete_PrioItems

# Register PrioItems in _libpygraphs:
_libpygraphs.PrioItems_swigregister(PrioItems)



